Support *FbtEnum.ts files
nkzw-tech/fbtee pull request #3
Opened 2024-12-13 12:03 UTC by alexandernanberg

Stacked on #2 (needed the automatic external detection)

I'm not sure the approach I've taken here is optimal, we could potentially use `ts-node` or `esbuild-register` but didn't have much luck with using them in an ESM environment. 

Now every enum file is transpiled using TS regardless of the extension, it might be wiser to only transpile `.tsx?` files. I can update to do that if you think it's a good idea

2024-12-16 23:00 UTC, cpojer commented
Did you try `--experimental-strip-types`? See https://nodejs.org/en/learn/typescript/run-natively

I do not mind that it's experimental, since it won't be experimental for too long.

Otherwise, I would much prefer to use Babel to strip TypeScript syntax instead of typescript because the typescript package is large and we are already using it in other places like for common strings: https://github.com/nkzw-tech/fbtee/blob/main/packages/babel-plugin-fbtee/src/bin/FbtCollector.tsx#L65-L88

2024-12-16 23:08 UTC, cpojer requested changes
see above

2024-12-17 07:43 UTC, alexandernanberg commented
No, but AFAICT we cannot enable a node.js flag without manually spawning a new process (or require consumers to pass a flag). But maybe I'm missing something?

Makes sense to use Babel instead of TS though. Updated the PR!

2024-12-17 11:31 UTC, cpojer commented
We should totally be in control of how the `bin` files are invoked, see https://github.com/nkzw-tech/athena-crisis/blob/main/codegen/generate-actions.tsx#L1C1-L2C1

Do you mind trying? I assume you have to make the changes to the src file, `pnpm build` and then see if it works or not.

2024-12-17 12:28 UTC, alexandernanberg commented
TIL! 

From what I can tell it works great. There is a warning logged when running the command that it's experimental but no big deal!

2024-12-17 12:37 UTC, cpojer commented
Just add --no-warnings. Since it's fbtee's cli, that's fine.

2024-12-17 13:14 UTC, alexandernanberg commented
Done! 👍

2024-12-18 00:42 UTC, cpojer commented
So elegant. Thank you!

2024-12-18 00:42 UTC, merged